---
COMMON:
  HOST: 127.0.0.1

  # Client IDs
  MASTER: 10 # Master client for retrieving ALL (manual and API) orders and trades
  COMMONCID: 0

  ACTIVE_STATUS:
  - ApiPending
  - PendingSubmit
  - PreSubmitted
  - Submitted
  BAR_FORMAT: "{desc:<10}{percentage:3.0f}%|{bar:25}{r_bar}{bar:-10b}"

  OPT_COLS: # Common option columns for anlaysis
   - ['conId', 'symbol', 'expiry', 'strike', 'right', 'dte', 'undPrice', 
   'contract', 'iv', 'sigma', 'sdev', 'margin', 'comm', 
   'lot_size', 'delta','gamma', 'vega', 'theta', 'optPrice', 'expPrice']

# ----------------------------
NSE:

  EXCHANGE: 'NSE'
  CURRENCY: 'INR'
  PORT: 3000
  PAPER: 3001 # For paper trades in IBG
  CID: 1
  MINDTE: 1
  MAXDTE: 60

  CALLSTDMULT: 2.3 # Min stdev multiple for calls
  PUTSTDMULT: -2.8 # Min stdev multiple for puts
  MINEXPROM: 1.5
  MINOPTSELLPRICE: 0.2

  BLACKLIST: # Ref: https://zerodha.com/margin-calculator/SPAN/
  - FINNIFTY
  - MIDCPNIFTY
  - NIFTYIT
 
  PREC: 0.05

# ----------------------------
SNP:

  EXCHANGE: 'SMART'
  CURRENCY: 'USD'
  PORT: 1300
  CID: 2
  PAPER: 1301 # For paper trades in IBG
  MINDTE: 1
  MAXDTE: 35

  CALLSTDMULT: 2 # Min stdev multiple for calls
  PUTSTDMULT: -2 #  Min stdev multiple for puts
  MINEXPROM: 1.2
  MINOPTSELLPRICE: 0.5
  

  BLACKLIST:
  - VXX

  PREC: 0.01
