---
COMMON:
  HOST: 127.0.0.1

  # Client IDs
  MASTER: 10 # Master client for retrieving ALL (manual and API) orders and trades
  COMMONCID: 0

  ACTIVE_STATUS: # For open orders
  - ApiPending
  - PendingSubmit
  - PreSubmitted
  - Submitted

  GAPBUMP: 0.5 # Bumps up sdev to cater for gap up / down in closed market
  
  BAR_FORMAT: "{desc:<10}{percentage:3.0f}%|{bar:25}{r_bar}{bar:-10b}"

  OPT_COLS: # Common option columns for anlaysis
   - ['conId', 'symbol', 'undPrice', 'expiry', 'strike', 'right', 
      'dte', 'sdev', 'lot_size', 'margin', 'comm', 'ask', 'bid', 
      'last', 'optPrice', 'expPrice', 'prop', 'rom']

  STATES:
    unsowed: ["#fffaf0" , "Fresh. No orders sown. No existing position.", "white"]
    orphaned: ["#a9a9a9" , "A long call or put option (positive) position that doesn't have an underlying position.", "darkgray"]
    perfect: ["#0f9d58" , "Ticker position present that is both covered and protected [or] Option position that is with a reap order.", "green"]
        
    uncovered: ["#f4b400" , "Ticker position present but with no covered call or put option and without any option open orders supporting it.", "yellow"]
    unprotected: ["#EF5350" , "Ticker position present but with no protective call or put option and without any option open orders.", "light-red"]
    imperfect: ["#9C27B0" , "Ticker position present that has no cover or protection options and without any option open orders.", "purple"]
        
    sowing : ["#4285f4" , "Naked Option orders present to be sowed.", "blue"]
    covering : ["#FFFDD0" , "Ticker position is protected with option but not covered and has option open orders to cover.", "cream"]
    protecting : ["#F48FB1" , "Ticker position is covered with option but not protected and has option open orders to protect. ", "pink"]
    perfecting : ["#C5E1A5" , "Ticker position with open orders for covering and protecting, that are not in position yet.", "light-green"]

    unreaped : ["#FFF59D" , "A naked call or put option that doesnt have an open order to reap.", "light-yellow"]

# ----------------------------
NSE:

  EXCHANGE: 'NSE'
  CURRENCY: 'INR'
  PORT: 3000
  PAPER: 3001 # For paper trades in IBG
  CID: 1

  MINDTE: 0
  MAXDTE: 60

  CALLSTDMULT: 1.3 # Min stdev multiple for calls
  PUTSTDMULT: -1.3 # Min stdev multiple for puts

  DTESTDEVLOW: 0.05 # Upper limit of adjustment to stdev based on DTE
  DTESTDEVHI: 1 # Lower limit of adjustment to stdev based on DTE
  
  DECAYRATE: 0.05 # Decay rate of the sdev adjustment curve on DTE

  MINEXPROM: 1.5

  MINOPTSELLPRICE: 0.25
  MAXOPTBUYPRICE: 0.05

  MAXNAKEDORDERS: 2 # Maximum number of naked orders per symbol

  BLACKLIST: # Ref: https://zerodha.com/margin-calculator/SPAN/
  - FINNIFTY
  - MIDCPNIFTY
  - NIFTYIT
 
  PREC: 0.05

  # Approximate - VaR margin of 0.75 + IV + 3% (IND) / 5% (STK) Exposure Margin
  PCT_FOR_COMPUTED_MARGIN: 0.15 

# ----------------------------
SNP:

  EXCHANGE: 'SMART'
  CURRENCY: 'USD'
  PORT: 1300
  CID: 2
  PAPER: 1301 # For paper trades in IBG

  MINDTE: 1
  MAXDTE: 60

  CALLSTDMULT: 2 # Min stdev multiple for calls
  PUTSTDMULT: -1.2 #  Min stdev multiple for puts

  DTESTDEVLOW: 0.1 # Upper limit of adjustment to stdev based on DTE
  DTESTDEVHI: 1.2 # Lower limit of adjustment to stdev based on DTE

  DECAYRATE: 0.05 # Decay rate of the sdev adjustment curve on DTE

  MINEXPROM: 2.5

  MINOPTSELLPRICE: 0.5
  MAXOPTBUYPRICE: 0.02
  
  MAXNAKEDORDERS: 2 # Maximum number of naked orders per symbol

  BLACKLIST:
  - VXX

  PREC: 0.01

  PCT_FOR_COMPUTED_MARGIN: 0.25 # Based on RULE OF 25
